//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAppointmentsManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOINTMENT
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime startSlotTime { get; set; }
        public System.DateTime endSlotTime { get; set; }
        public Nullable<int> PATIENT_patient { get; set; }
        public int DOCTOR_username { get; set; }
        public bool isAvailable { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual PATIENT PATIENT { get; set; }
    }
}
